CREATE TABLE Question(
    id SERIAL PRIMARY KEY,
    userId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    text VARCHAR(255) NOT NULL,
    status INT NOT NULL DEFAULT 0,
    timestamp TIMESTAMP NOT NULL,
    upVotes INT NOT NULL DEFAULT 0,
    downVotes INT NOT NULL DEAFULT 0,
    FOREIGN KEY (userId) REFERENCES User(id),
)