CREATE TABLE QuestionTags(
    questionId INT NOT NULL,
    tagId INT NOT NULL,
    FOREIGN KEY (questionId) REFERENCES Question(id) ON DELETE CASCADE,
    FOREIGN KEY (tagId) REFERENCES Tags(id) ON DELETE CASCADE
)